http-out:
  url: "earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson"
scheduler:
  delay-millis: "60000"
  thread-count: 1
#scheduler2:
#  delay-millis: "10"
#  thread-count: 1
#kafka-out:
#  topic: "test"
#  brokers: "192.168.100.100:9091,192.168.100.100:9092,192.168.100.100:9093"